# coding: utf-8

"""
    Aspose OMR Cloud V5 API

    Aspose OMR Cloud V5 API  # noqa: E501

    OpenAPI spec version: V5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import sys
from setuptools import setup, find_packages  # noqa: H301

NAME = "aspose-omr-cloud"
VERSION = "23.1.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Python library for communicating with the Aspose.OMR Cloud API",
    author="Aspose Pty Ltd",
    author_email="aspose.cloud@asposeptyltd.com",
    url="https://github.com/aspose-omr-cloud/aspose-omr-cloud-python",
    keywords=["aspose", "aspose cloud", "omr", "answer sheet"],
    license="MIT",
    install_requires=[
        'scikit-learn',
    ],
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Aspose.OMR for Cloud is a REST API that helps you to perform optical mark recognition in the cloud. We provide a series of SDKs. Along with that, you can get binaries to start working immediately and recognize various OMR forms.
    Developers can embed optical recognition in any type of application to extract data from images of tests, exams, questionnaires, surveys, etc. In the repository you can find examples on how to start using Aspose.OMR API in your project.
    """
)
