# coding: utf-8

"""
    Aspose.OMR for Cloud API Reference

    Aspose.OMR for Cloud helps performing optical mark recognition in the cloud

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.aspose_response import AsposeResponse
from .models.file_info import FileInfo
from .models.omr_function_param import OMRFunctionParam
from .models.omr_response_details import OMRResponseDetails
from .models.omr_response_content import OmrResponseContent
from .models.omr_response_info import OmrResponseInfo
from .models.payload import Payload
from .models.recognition_statistics import RecognitionStatistics
from .models.server_stat import ServerStat
from .models.omr_response import OMRResponse

# import apis into sdk package
from .apis.omr_api import OmrApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration
