# coding: utf-8

"""
Copyright (c) 2018 Aspose Pty Ltd. All Rights Reserved.

Licensed under the MIT (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

      https://github.com/aspose-omr-cloud/aspose-omr-cloud-python/blob/master/LICENSE

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.



    Aspose.OMR for Cloud API Reference

    Aspose.OMR for Cloud helps performing optical mark recognition in the cloud

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from .aspose_response import AsposeResponse
from .file_info import FileInfo
from .omr_function_param import OMRFunctionParam
from .omr_response_details import OMRResponseDetails
from .omr_response_content import OmrResponseContent
from .omr_response_info import OmrResponseInfo
from .payload import Payload
from .recognition_statistics import RecognitionStatistics
from .server_stat import ServerStat
from .omr_response import OMRResponse
